Update paymentlink with unit test
razorpay/razorpay-ruby pull request #135
Opened 2022-03-22 10:48 UTC by ankitdas13

2022-05-10 06:48 UTC, sofiya02 reviewed
Readme LGTM

2022-05-25 11:04 UTC, sonyy-m requested changes

2022-05-25 11:04 UTC, sonyy-m commented on lib/razorpay/payment_link.rb
> +  # PaymentLink API allows you to create and fetch customers on Razorpay
check and update the comment

2022-05-25 11:04 UTC, sonyy-m commented on test/fixtures/fake_payment_link.json
> +  }
Fix indentation and add new line at end of file

2022-05-25 11:04 UTC, sonyy-m commented on test/fixtures/payment_link_collection.json
> +  }
Fix indentation and add new line at end of file

2022-05-25 11:04 UTC, sonyy-m commented on test/fixtures/payment_link_response.json
> +}
add new line at end of file

2022-05-25 11:06 UTC, sonyy-m commented on documents/paymentLink.md
> +Razorpay::PaymentLink.edit(paymentLinkId, para_attr)
Add headers and convert parameter to json to avoid faulty key errors

2022-05-30 11:54 UTC, ankitdas13 commented on test/razorpay/test_payment_link.rb
> +      payment_link = Razorpay::PaymentLink.fetch(@payment_link_id).edit(para_attr.to_json)
fixed edit function

2022-05-30 11:57 UTC, ankitdas13 commented on documents/paymentLink.md
> +  "accept_partial": true,
have taken from this doc [reference](https://razorpay.com/docs/api/payments/payment-links/#sample-codes-for-upi-payment-links)

2022-05-30 11:57 UTC, ankitdas13 commented on lib/razorpay/payment_link.rb
> +  # PaymentLink API allows you to create and fetch customers on Razorpay
fixed class comments

2022-06-01 04:39 UTC, sonyy-m approved these changes
LGTM

2022-06-01 08:39 UTC, merged