update subscription & unit test with test case
razorpay/razorpay-ruby pull request #141
Opened 2022-04-04 07:53 UTC by ankitdas13

2022-05-09 09:29 UTC, sofiya02 reviewed
Readme LGTM

2022-05-26 09:40 UTC, sonyy-m requested changes
Fix indentation and add newline at end of file in all json files

2022-05-26 09:40 UTC, sonyy-m commented on lib/razorpay/request.rb
> -
why the delete request was removed?

2022-06-01 10:13 UTC, sonyy-m approved these changes
LGTM

2022-06-01 10:54 UTC, merged